name: Release new versions

on:
  push:
    tags:
      - "v*" # Matches SemVer tags

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout
      id-token: write # Required for Trusted Publishing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Publish crate
        run: cargo publish

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            For details, see CHANGELOG.md.

            See changes in [compare view](https://github.com/zabackary/vexide-motorgroup/compare/${{ github.previous_ref }}...${{ github.ref }})
          draft: false
          prerelease: false
