name: Release new versions

on:
  push:
    tags:
      - "v*" # Matches SemVer tags

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout
      id-token: write # Required for Trusted Publishing
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          profile: minimal
          toolchain: nightly
          components: rust-src

      - uses: rust-lang/crates-io-auth-action@v1
        id: auth

      - name: Publish crate
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            For details, see CHANGELOG.md.

            See changes in [compare view](https://github.com/zabackary/vexide-motorgroup/compare/${{ github.previous_ref }}...${{ github.ref }})
          draft: false
          prerelease: false
